### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by gerardoCD** [RayDeCampo/nodejs-xirr#8]
I am trying to do these operations but it sends me the following error:

![Captura de Pantalla 2020-09-15 a la(s) 19 08 05](https://user-images.githubusercontent.com/25653518/93277012-cae67280-f786-11ea-911e-c53b317bec54.png)

my code is 

let arrays = [

  { amount: 644444444, when: new Date('2022-03-18T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2022-02-15T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2022-01-16T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-12-16T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-11-16T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-10-16T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-09-16T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-08-16T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-07-17T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-06-16T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-05-17T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-04-16T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-03-17T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-02-14T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2021-01-15T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2020-12-15T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2020-11-15T00:00:00.000Z') },
  { amount: 644444443, when: new Date('2020-10-15T00:00:00.000Z') },
  { amount: 7229120000, when: new Date('2020-09-15T00:00:00.000Z') },
  { amount: -11600000000, when: new Date('2020-09-15T00:00:00.000Z') },
]

let rate = xirr(arrays);

  console.log('rate :', rate);

In excel works fine 

i
I hope you can help me

**Comment by RayDeCampo** [comment]
Usually this can be avoided by defining a better value for `guess` in the `options` passed.
